### ISSUE TITLE
[BUG] No Module Manifest Found

### ISSUE THREAD

**Issue by Armandeus66** [digitalshadowhawk/pf2e-subsystem-helper#2]
I got the "no module manifest found" error for this module when doing a general module update in Foundry today.

**Comment by digitalshadowhawk** [comment]
That's because the auto-generated url for the module manifest points to the latest release on github, but there's no version released that isn't a pre-release yet. Foundry does two checks for new module versions though, one from the module manifest url and the other from the list of available versions on the module marketplace, which I've made sure to keep up to date.

For now, if there's an update, it will still properly update without any error message, but throw an error if there isn't. I'll leave this issue open for now, that way when I publish a full release I can close it and let you know.

**Comment by Armandeus66** [comment]
Thanks. I usually don't see this error from other modules, so I thought I'd report it.
